[package]
name = "linfa"
version = "0.2.1"
authors = [
    "Luca Palmieri <rust@lpalmieri.com>",
    "Lorenz Schmidt <bytesnake@mailbox.org>",
    "Paul Körbitz <koerbitz@google.com>"
]
description = "A Machine Learning framework for Rust"
edition = "2018"
license = "MIT/Apache-2.0"

repository = "https://github.com/rust-ml/linfa"
readme = "README.md"

keywords = ["machine-learning", "linfa", "ai", "ml"]
categories = ["algorithms", "mathematics", "science"]

exclude = [".github/"]

[dependencies]
num-traits = "0.2"
ndarray = { version = "0.13", default-features = false }

[dev-dependencies]
rand = "0.7"
ndarray-rand = "0.12"
approx = "0.3"

[workspace]
members = [
    "linfa-clustering",
    "linfa-reduction",
    "linfa-kernel",
    "linfa-linear",
    "linfa-logistic",
    "linfa-trees",
    "linfa-svm",
    "linfa-hierarchical",
    "linfa-ica",
    "linfa-bayes",
]

[profile.release]
opt-level = 3
