[package]
name = "linfa"
version = "0.1.1"
authors = ["Luca Palmieri <rust@lpalmieri.com>"]
description = "A Machine Learning framework for Rust"
edition = "2018"
license = "MIT/Apache-2.0"

repository = "https://github.com/LukeMathWalker/linfa"
readme = "README.md"

keywords = ["machine-learning", "linfa", "ai", "ml"]
categories = ["algorithms", "mathematics", "science"]

[dependencies]
ndarray = { version = "0.13", default-features = false }
num-traits = "0.1.32"

linfa-clustering = { path = "linfa-clustering", version = "0.1" }
linfa-trees = { path = "linfa-trees", version = "0.1" }
linfa-reduction = { path = "linfa-reduction", version = "0.1" }
linfa-linear = { path = "linfa-linear", version = "0.1" }
linfa-logistic = { path = "linfa-logistic", version = "0.1" }
linfa-svm = { path = "linfa-svm", version = "0.1" }
linfa-hierarchical = { path = "linfa-hierarchical", version = "0.1" }

[dev-dependencies]
rand = "0.7"
ndarray-rand = "0.11"
rand_isaac = "0.2.0"
ndarray-npy = { version = "0.5", default-features = false }
approx = "0.3"

[workspace]
members = [
    "linfa-clustering",
    "linfa-reduction",
    "linfa-kernel",
    "linfa-linear",
    "linfa-logistic",
    "linfa-trees",
    "linfa-svm",
    "linfa-hierarchical",
    "linfa-ica",
    "linfa-bayes",
]

[profile.release]
opt-level = 3
