on: [push, pull_request]

name: Codequality Lints

jobs:
  codequality:
    name: codequality
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - 1.42.0
          - nightly
          - beta
          - stable

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.toolchain }}
          override: true
          components: rustfmt, clippy

      - name: Run cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: Run cargo clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all-targets --all-features -- -D warnings

  coverage:
    name: coverage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: rustfmt, clippy

      - name: Get rustc version
        id: rustc-version
        run: echo "::set-output name=version::$(cargo +nightly --version | cut -d ' ' -f 2)"
        shell: bash

      - uses: actions/cache@v2
        id: tarpaulin-cache
        with:
          path: |
            ~/.cargo/bin/cargo-tarpaulin
          key: ${{ runner.os }}-cargo-${{ steps.rustc-version.outputs.version }}

      - name: Install tarpaulin
        if: steps.tarpaulin-cache.outputs.cache-hit != 'true'
        run: cargo +nightly install cargo-tarpaulin

      - name: Generate code coverage
        run: |
          cargo +nightly tarpaulin --verbose --all-features --timeout 120 --out Xml

      - name: Upload to codecov.io
        uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: true
